config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :users
  resources :animations
  resources :artists

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #customerzise path for adding animation
  get '/add_animation/:animation_id' => 'users#add_animation', as: 'add_animation'
  get '/unlike_animation/:animation_id' => 'users#unlike_animation', as: 'unlike_animation'

end

app/models/animation.rb
# == Schema Information
#
# Table name: animations
#
#  id          :bigint(8)        not null, primary key
#  artist_id   :integer
#  name        :string
#  description :text
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Animation < ApplicationRecord
  belongs_to :artist
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ApplicationRecord
  has_many :animations
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ApplicationRecord
  has_and_belongs_to_many :animations
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_and_belongs_to_many :animations
end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
  def index #show all animation
    @animations = Animation.all - @current_user.animations
  end

  def show
    @animation = Animation.find(params[:id])
    @artist = @animation.artist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present? # This prevents horrors when reseeding
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index #show all artist
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by :email => params[:email]
    if @user.present? && @user.authenticate(params[:password])
      log_in @user
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path # Redirect to home if the account is valid
    else
      flash[:error] = @user.errors.full_messages.first
      redirect_to new_user_path # Let them retry the form again
    end
  end

  def add_animation
    animation = Animation.find(params[:animation_id])
    @current_user.animations << Animation.find(params[:animation_id])
    redirect_to root_path
  end

  def unlike_animation
    @current_user.animations.delete(Animation.find(params[:animation_id]))
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/animations_helper.rb
module AnimationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animations/index.html.erb
<div class="<%= controller_name %>">
<% if @current_user.present? %>

  <h2>All Animations:</h2>


      <% @animations.each do |animation| %>
        <div class="index-animation-grid">
      <%= image_tag(animation.image,:alt => animation.name, :class => 'animation_thumbnail') %>
        <%= link_to (animation.name), animation_path(animation), :class => 'animation_name'%>
        <%= button_to "Add to My Animation", add_animation_path(animation.id), :class => 'animation_thumbnail', :method => 'get' %>
        <br />
        </div>
      <% end %>


  <%= button_to "Back", root_path, :method => :get %>

<% else %>
  <div>
    <h1>Welcome to MangaStore</h1>
    <p>© 2019</p >
  </div>
</div>
<% end %>

app/views/animations/show.html.erb
<div class="<%= controller_name %>">
  <% if @current_user.present? %>
  <div >
  <h2><%= @animation.name %> </h2>
  <p id="description"><%= @animation.description %> </p>
    <%= image_tag(@animation.image,:class =>'animation_thumbnail') %>
  </div>

  <div class="artist">Artist: <%= link_to @animation.artist.name, artist_path(@animation.artist) %></div>


  <%= button_to "Back", root_path, :method => :get %>

  <% else %>
  <div>
    <h1>Welcome to MangaStore</h1>

  </div>
  <% end %>
</div>

app/views/artists/index.html.erb
<h1>All Artists</h1>

<% @artists.each do |artist| %>

  <div class="index-artist-grid">
    <%= link_to image_tag(artist.image, :alt => artist.name, :class => 'artist_thumbnail'), artist if artist.image.present? %>

      <ul>
        <li><%= link_to artist.name, artist  %></li>
      </ul>
  </div>
<% end %>

app/views/artists/show.html.erb
<div class="<%= controller_name %>">
<h2><%= @artist.name %></h2>

<div>
  <%= image_tag(@artist.image, :class =>'artist_thumbnail') %>
</div>

<p class="description">Description: <%= @artist.description %></p>



<%= button_to "Back", root_path, :method => :get %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManga</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'blackpaw.ico' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="nav justify-content-end">
      <ul class="nav nav-pills">
        <li class="nav-item">
        <%= link_to 'Home', root_path %>
        </li>
        <% if @current_user.present? %>
        <li class="nav-item">
          <%= link_to "Sign out", login_path, :method => 'delete' %>
        </li>
          <li class="nav-item"><%= @current_user.email %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_path, :class => "btn-signup"  %></li>
          <li><%= link_to 'Sign in', login_path, :class => "btn-login"%></li>
        <% end %>
      </ul>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="<%= controller_name %>">
<% if @current_user.present? %>

  <h2>My Animation:</h2>
  <div class="mymanga">
    <% @current_user.animations.each do |animation| %>
      <%= image_tag(animation.image, :class =>'animation_thumbnail') %>
      <%= link_to (animation.name), animation_path(animation), :class => 'animation_name'%>
      <%= button_to "Unlike", unlike_animation_path(animation.id), :method => :get %>
      <br/>
    <% end %>
  </div>
  <%= button_to "Browse Animation", { :action => "index", :controller => 'animations' }, :method => :get %>


<% else %>
  <div >
    <h1 class="rainbow">Welcome to Animation World</h1>
  </div>
  <footer>
    <p>Jing © 2019</p>
    <div class="whitesocials">
      <a href="https://github.com/Jing1107"><%= image_tag '/assets/githubwhitegood.png', :class => "whiteicon"%></a>
      <a href="https://www.linkedin.com/in/jing-sissi-dong-960b94122/"><%= image_tag '/assets/linkediniconwhite.png', :class => "whiteicon linkedinicon"%></a>
      <a href="https://twitter.com/Jing11072"> <%= image_tag '/assets/twittericonwhite.png', :class => "whiteicon twittericon" %></a>
    </div>
  </footer>


<% end %>
</div>

app/views/session/new.html.erb
<div class="<%= controller_name %>">
<%= form_tag login_path do %>
  <h1>Please sign in</h1>

  <% if flash[:error] %>
    <div>
      <%= flash[:error]%>
    </div>
  <% end %>
    <div class="loginWrapper"><%= label_tag :email,nil %>
    <%= email_field_tag :email,nil, :class =>'emailLabel',:placeholder => 'Email address'%></div>
    <div class="loginWrapper"><%= label_tag :password,nil %>
    <%= password_field_tag :password, nil,:class =>'passwordLabel' ,:placeholder => 'Password' %></div>

  <%= submit_tag "Log In", :class =>' loginbtn btn btn-lg btn-primary btn-block'%>
  <!-- <p>Jing © 2019</p > -->
<% end %>
</div>

app/views/users/new.html.erb
<div class="<%= controller_name %>">
<%= form_for @user do |f| %>
  <h1>Please sign up </h1>
  <% if flash[:error] %>
    <div>
      <%= flash[:error]%>
    </div>
  <% end %>
  <div class="loginWrapper">
    <%= f.label :email%>
    <%= f.email_field :email, :class =>'email', :placeholder => 'Email address'%>
  </div>

  <div class="lohinWrapper">
    <%= f.label :password %>
    <%= f.password_field :password, :class =>'password', :placeholder => 'Password' %>
  </div>

  <div class="loginWrapper">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class =>'password_confirmation', :placeholder => 'Password' %>
  </div>


  <%= f.submit "Sign Up Now", :class =>' signbtn btn btn-lg btn-primary btn-block' %>
<% end %>
</div>